### ISSUE TITLE
navbar menu not active when gone to home page

### ISSUE THREAD

**Issue by 16vmini** [DeannaGreen/room_booker#13]
navbar menu not active when gone to home page
![image](https://user-images.githubusercontent.com/1812460/43707894-06b14eba-9961-11e8-9ec8-457c657d736f.png)

**Comment by DeannaGreen** [comment]
navbar is only showing sections as active if you are on the index pages no where else

**Comment by DeannaGreen** [comment]
fixed so that when you go onto any page relating to rooms for example rooms in the navbar will be active
