### ISSUE TITLE
roombookings issues on heroku

### ISSUE THREAD

**Issue by 16vmini** [DeannaGreen/room_booker#26]
![image](https://user-images.githubusercontent.com/1812460/44572082-a91e8b00-a77a-11e8-8ccd-26e52bc52f07.png)

**Comment by 16vmini** [comment]
ok , this is related to bad data , ie missing user ID info ... 

we should remember to take this into account if we add columns etc, and create or delete data so errros dont happen

**Comment by DeannaGreen** [comment]
I have cleared my database and then migrated to heroku and we still have this problem, so not sure if it is to do with data

**Comment by DeannaGreen** [comment]
16vmini fixed by fixing migration scripts as one still had room_id which made them fail
