### ISSUE TITLE
Only allow a user that is an admin to edit home page info 

### ISSUE THREAD

**Issue by 16vmini** [DeannaGreen/room_booker#30]
Only allow a user that is an admin to edit home page info 

in devise there should be a way add a Admin role to certain users ..

https://github.com/plataformatec/devise/wiki/How-To:-Add-an-Admin-Role

**Comment by DeannaGreen** [comment]
I have added the Admin. @16vmini where are referring to when you say homepage?

**Comment by 16vmini** [comment]
@DeannaGreen  this can be left for now , as we have a homepage table , with some fields on it , but we are not using it at moment ...
